config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'

  get 'home/info'

  get "fafsa_apps/:id/check/", to: "fafsa_apps#check"
  
  get "fafsa_apps/:id/submit/", to: "fafsa_apps#submit"
 

  resources :fafsa_apps
 
  
  resources :users, controllers: "fafsa_apps" do
    resources :fafsa_apps
  end



  get 'users/apps'


  devise_for :users, :path_prefix => 'd'
  

  match '/users/:id',     to: 'users#show',       via: 'get'
 
  match '/users',   to: 'users#index',   via: 'get'
  
  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  # end
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fafsa_app.rb
class FafsaApp < ApplicationRecord

    belongs_to :user, foreign_key: "user_id"

    

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :fafsa_apps, dependent: :delete_all, validate: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :dob, :first_name, :last_name, :username, :sex, :phone, :address, :city, :state, :zip, :student)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :dob, :first_name, :last_name, :username, :sex, :phone, :address, :city, :state, :zip)}
         end
    
end

app/controllers/fafsa_apps_controller.rb
class FafsaAppsController < ApplicationController
  before_action :set_fafsa_app, only: %i[ show edit update destroy ]

  # GET /fafsa_apps or /fafsa_apps.json
  def index
    @fafsa_apps = FafsaApp.all
   
  end

  # GET /fafsa_apps/1 or /fafsa_apps/1.json
  def show
  
    @fafsa_app = FafsaApp.find(params[:id])
    id = @fafsa_app.user_id
    @user = User.find_by id: id
  
  
    @fafsa_apps = FafsaApp.all
  end

  #check for prequalification
  def check
    @fafsa_app = FafsaApp.find(params[:id])

   
  end

  def submit
    @fafsa_apps = FafsaApp.all
    @fafsa_app = FafsaApp.find(params[:id])
    id = @fafsa_app.user_id
    @user = User.find_by id: id
    @user.dob = @user.dob.to_s.unpack('A4xA2xA2').rotate.join('/')

    

  end



  # GET /fafsa_apps/new
  def new
    @fafsa_app = FafsaApp.new
  end

  # GET /fafsa_apps/1/edit
  def edit
  end

  # POST /fafsa_apps or /fafsa_apps.json
  def create
    @fafsa_app = FafsaApp.new(fafsa_app_params)
   

    respond_to do |format|
      if @fafsa_app.save
      
        format.html { redirect_to @fafsa_app , notice: "Fafsa app was successfully created." }
        format.json { render :check, status: :created, location: @fafsa_app  }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fafsa_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fafsa_apps/1 or /fafsa_apps/1.json
  def update
    respond_to do |format|
      if @fafsa_app.update(fafsa_app_params)
        format.html { redirect_to @fafsa_app, notice: "Fafsa app was successfully updated." }
        format.json { render :show, status: :ok, location: @fafsa_app }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fafsa_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fafsa_apps/1 or /fafsa_apps/1.json
  def destroy
    @fafsa_app.destroy
    respond_to do |format|
      format.html { redirect_to fafsa_apps_url, notice: "Fafsa app was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fafsa_app
      @fafsa_app = FafsaApp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fafsa_app_params
      
      params.require(:fafsa_app).permit(:mid_init,:drivers_license,:high_school_name, :high_school_city, :high_school_state, :housing_plans, :dep, :kids, :married, :drivers_license_st,  :foster_care, :work_study, :drivers_license_num, :high_school, :citizen, :alien_num, :conviction, :parent_edu, :parent_edu2, :receive_aid, :application_year, :current_grade, :bachelors, :degree_applied, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
       
    end
    
    def show
       
        @user = User.find(params[:id])

        @user.dob = @user.dob.to_s.unpack('A4xA2xA2').rotate.join('/')
    end

    def apps

       
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fafsa_apps_helper.rb
module FafsaAppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parent_usrs_helper.rb
module ParentUsrsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/student_parents_helper.rb
module StudentParentsHelper
end

app/views/fafsa_apps/_form.html.erb
<%= form_with(model: fafsa_app) do |form| %>
  <% if fafsa_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fafsa_app.errors.count, "error") %> prohibited this fafsa_app from being saved:</h2>

      <ul>
        <% fafsa_app.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="form-div">
    <div class="field">
      What is the highest education completed by one parent?
        <%form.label :parent_edu %><br/>
        <%= form.select :parent_edu, ["","Middle School/Jr. High", "High School", "College or beyond", "Other/unknown"] ,{}, {:class=> "input" }%>
    </div>
            
            
    <div class="field">
      What is the highet education completed by the other parent?
        <% form.label :parent_edu2 %><br/>
        <%= form.select :parent_edu2, ["","Middle School/Jr. High", "High School", "College or beyond", "Other/unknown"],{}, {:class=> "input" } %>
    </div>
  
    <div class="field">
      Do you have a drivers license?
        <%form.label :drivers_license %>
        <%= form.select :drivers_license, ["",'Yes', 'No'],{}, {:class=> "input" }%>
    </div>


    <div class="field">
      What is your Drivers License number?
        <% form.label :drivers_license_num %><br/>
        <%= form.text_field :drivers_license_num, class:"input" %>
    </div>

    <div class="field">
      Drivers License St
        <% form.label :drivers_license_st %><br/>
        <%= form.text_field :drivers_license_st, class:"input" %>
    </div>


    <div class="field">
        What is your alien registration number?
          <% form.label :alien_num %><br/>
          <%= form.text_field :alien_num, class:"input"%>
    </div>

    <div class="field"> 
        Have you ever been in foster care?
          <%form.label :foster_care %><br/>
          <%= form.select :foster_care, ['', 'Yes', 'No'],{}, {:class=> "input" } %>
    </div>


    <div class="field">
        What high school did you attend?
          <% form.label :high_school_name %><br/>
          <%= form.text_field :high_school_name, {:class=> "input" } %>
    </div> 

    <div class="field">
        In which city is your high school?
          <% form.label :high_school_city %><br/>
          <%= form.text_field :high_school_city , {:class=> "input" } %>
    </div>

    <div class="field">
        In which state is your high school?
          <% form.label :high_school_st %><br/>
          <%= form.select :high_school_st, ['','Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii',  'Idaho', 'Illinois', 'Indiana','Iowa', 'Kansas', 'Kentucky',  'Louisiana','Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri','Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico','New York', 'North Carolina','North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina','South Dakota', 'Tennessee','Texas', 'Utah', 'Vermont','Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming' ],{}, {:class=> "input" } %>
    </div>

    <div class="field">
        Would you be interested in doing a work study program?
          <% form.label :work_study %><br/>
          <%= form.select :work_study, ['', 'Yes', 'No', 'I dont know'],{}, {:class=> "input" } %>
    </div> 
  
    <div class="field">
        What are you housing plans for your time in college?
          <% form.label :housing_plans%><br/>
          <%= form.select :housing_plans, ['', 'On Campus', 'With Parent','Off Campus'],{}, {:class=> "input" } %>
    </div>

    <div class="field">
        Do you have children who depend 50% or more on you?
          <% form.label :kids %><br/>
          <%= form.select :kids, ['', 'Yes', 'No'],{}, {:class=> "input" } %>
    </div>

    <div class="field">
        What is your martial status?
          <% form.label :married %><br/>
          <%= form.select :married, ['', 'I am single', 'I am married/remarried','I am separated','I am divorced or widowed'] ,{}, {:class=> "input" }%>
    </div>
    <div class="field">
        Do you have any dependents, who are not children, who depende 50% or more on you?
          <%form.label :dep %><br/>
          <%= form.select :dep, ['', 'Yes', 'No'] ,{}, {:class=> "input" }%>
    </div>

</div> 

<div class="actions">
  <%= form.submit "Finish" %>
</div>

<% end %>

app/views/fafsa_apps/_form1.html.erb
<div  class="big-box"> 
<%= form_with(model: fafsa_app) do |form| %>
    <% if fafsa_app.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(fafsa_app.errors.count, "error") %> prohibited this fafsa_app from being saved:</h2>
  
        <ul>
          <% fafsa_app.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= form.hidden_field :user_id, value: current_user.id %>
  
   
<div class="horizontal-con">

    <div class="form-div">
          <div class="field">
            For which academic year are you applying?
              <%form.label :application_year %><br />
              <%= form.select :application_year, ['2021 - 2022'],{}, {:class=> "input" } %>
            </div>

          <div class="field">
              Have you received a Federal Pell Grant before?
                  <%form.label :receive_aid %><br />
                  <%= form.select :receive_aid, ["","I have received aid before", "I have not received aid before"],{}, {:class=> "input" } %>
          </div>
              
          <div class="field">
            Have you been convicted of a drug offense while recieving aid? 
                    <%form.label :conviction %><br />
                    <%= form.select :conviction, [ "I have not been convicted ", "I have been convicted"], {}, {:class=> "input" }%> 
          </div>

          <div class="field">
            Which best describes your grade level?
            <% form.label :current_grade %><br />
            <%= form.select :current_grade, ['', 'Never attended college/1st yr.', 'Attended college before/1st yr.', '2nd yr./sophomore', '3rd yr./junior', '4th yr./senior', '5th yr./other undergraduate', '1st yr. college graduate/professional (MBA, MD, PhD, etc.)', 'Continuing graduate/professional or beyond (MBA, MD, PhD, etc.)' ],{}, {:class=> "input" } %>
          </div>
          
          <div class="field">
                What is your citizenship status?
                    <% form.label :citizen %><br />
                    <%= form.select :citizen, ['','Yes, I am a U.S. citizen (or U.S. national)', 'No, but I am an eligible noncitizen', 'No, I am not a citizen or eligible noncitizen', "I do not know."] ,{}, {:class=> "input" }%>
          </div>

          <div class="field">
            What type of high school do you have?
              <% form.label :high_school %><br />
              <%= form.select :high_school, ['','High school diploma', 'GED certificate or state authorized high school equivalent certificate','Home schooled', 'None of the above'],{}, {:class=> "input" } %>
          </div>

          <div class="field">
            Will you have your Bachelors by the time you start your school year? 
              <% form.label :bachelors %><br />
              <%= form.select :bachelors, ['', 'No', 'Yes'],{}, {:class=> "input" } %>
          </div>

          <div class="field">
            For which degree have you applied?
              <% form.label :degree_applied %><br />
              <%= form.select :degree_applied, ['1st bachelor\'s degree','2nd bachelor\'s degree', 'Associate degree (occupational or technical program)','Associate degree (general education/transfer program)','Certificate/diploma (occupational/technical/education program of less than 2 yr.)','Certificate/diploma (occupational/technical/education program of at least 2 yr.)','Teaching credential program (nondegree program)','College graduate/professional degree (MBA, MD, PhD, etc.)','Other/undecided'] ,{}, {:class=> "input" }%>
          </div>

          <div class="actions">
              <%= form.submit "Do I qualify?",  class:"nav submit "%>
          </div>

      </div>

 <% end %> 

  <div class="right-box">
    extra info here
  </div>
</div>
           

  

  

app/views/fafsa_apps/_parent_info.html.erb
<%= form_with(model: fafsa_app) do |form| %>
    <% if fafsa_app.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(fafsa_app.errors.count, "error") %> prohibited this fafsa_app from being saved:</h2>
  
        <ul>
          <% fafsa_app.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  


    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="form-div">
  <div class="field">
    What is the highest education completed by one parent?
    <%form.label :parent_edu %><br/>
    <%= form.select :parent_edu, ["","Middle School/Jr. High", "High School", "College or beyond", "Other/unknown"] ,{}, {:class=> "input" }%>
  </div>
            
            
  <div class="field">
    What is the highet education completed by the other parent?
    <% form.label :parent_edu2 %><br/>
    <%= form.select :parent_edu2, ["","Middle School/Jr. High", "High School", "College or beyond", "Other/unknown"],{}, {:class=> "input" } %>
  </div>
</div>

<div class="actions">
  <%= form.submit "Finish" %>
</div>
<% end %>

app/views/fafsa_apps/_student_bg.html.erb
<%= form_with(model: fafsa_app) do |form| %>
  <% if fafsa_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fafsa_app.errors.count, "error") %> prohibited this fafsa_app from being saved:</h2>

      <ul>
        <% fafsa_app.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-div">
  <div class="field">
  
  Do you have a drivers license?
    <%form.label :drivers_license %>
    <%= form.select :drivers_license, ["",'Yes', 'No'],{}, {:class=> "input" }%>
  </div>
 

  <div class="field">
  What is your Drivers License number?
    <% form.label :drivers_license_num %><br/>
    <%= form.text_field :drivers_license_num, class:"input" %>
  </div>

  <div class="field">
  Drivers License St
  <% form.label :drivers_license_st %><br/>
  <%= form.text_field :drivers_license_st, class:"input" %>
</div>


  <div class="field">
  What is your alien registration number?
    <% form.label :alien_num %><br/>
    <%= form.text_field :alien_num, class:"input"%>
  </div>


  <div class="field"> 
  Have you ever been in foster care?
    <%form.label :foster_care %><br/>
    <%= form.select :foster_care, ['', 'Yes', 'No'],{}, {:class=> "input" } %>
  </div>

 
 

<% end %>

app/views/fafsa_apps/_student_dep.html.erb
<%= form_with(model: fafsa_app) do |form| %>
    <% if fafsa_app.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(fafsa_app.errors.count, "error") %> prohibited this fafsa_app from being saved:</h2>
  
        <ul>
          <% fafsa_app.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="form-div">
        <div class="field">
          Do you have children who depend 50% or more on you?
            <% form.label :kids %><br/>
            <%= form.select :kids, ['', 'Yes', 'No'],{}, {:class=> "input" } %>
        </div>

        <div class="field">
          What is your martial status?
            <% form.label :married %><br/>
            <%= form.select :married, ['', 'I am single', 'I am married/remarried','I am separated','I am divorced or widowed'] ,{}, {:class=> "input" }%>

        <div class="field">
          Do you have any dependents, who are not children, who depende 50% or more on you?
            <%form.label :dep %><br/>
            <%= form.select :dep, ['', 'Yes', 'No'] ,{}, {:class=> "input" }%>
        </div>
    
    </div> 
   
      

<% end %>

app/views/fafsa_apps/_student_financials.html.erb
<%= form_with(model: fafsa_app) do |form| %>
    <% if fafsa_app.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(fafsa_app.errors.count, "error") %> prohibited this fafsa_app from being saved:</h2>
  
        <ul>
          <% fafsa_app.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
here is info about taxes and income

<%= form.hidden_field :user_id, value: current_user.id %>

<% end %>

app/views/fafsa_apps/edit.html.erb
<h1>Complete the FAFSA App</h1>

<%= render 'form', fafsa_app: @fafsa_app %>



<%= link_to 'Back', :back %>

app/views/fafsa_apps/index.html.erb
<h1>Fafsa Apps</h1>

<table>
  <thead>
    <tr>
      <th>Drivers license</th>
      <th>Drivers license st</th>
      <th>Drivers license num</th>
      <th>Citizen</th>
      <th>Alien num</th>
      <th>Conviction</th>
      <th>Parent edu</th>
      <th>Parent edu2</th>
      <th>Receive aid</th>
      <th>Application year</th>
      <th>Current grade</th>
      <th>Bachelors</th>
      <th>Degree applied</th>
      <th>user_id</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @fafsa_apps.each do |fafsa_app| %>
      <tr>
        <td><%= fafsa_app.drivers_license %></td>
        <td><%= fafsa_app.drivers_license_st %></td>
        <td><%= fafsa_app.drivers_license_num %></td>
        <td><%= fafsa_app.citizen %></td>
        <td><%= fafsa_app.alien_num %></td>
        <td><%= fafsa_app.conviction %></td>
        <td><%= fafsa_app.parent_edu %></td>
        <td><%= fafsa_app.parent_edu2 %></td>
        <td><%= fafsa_app.receive_aid %></td>
        <td><%= fafsa_app.application_year %></td>
        <td><%= fafsa_app.current_grade %></td>
        <td><%= fafsa_app.bachelors %></td>
        <td><%= fafsa_app.degree_applied %></td>
        <td><%= fafsa_app.user_id %></td>
        <td><%= link_to 'Show', fafsa_app %></td>
        <td><%= link_to 'Edit', edit_fafsa_app_path(fafsa_app) %></td>
        <td><%= link_to 'Destroy', fafsa_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fafsa App', new_fafsa_app_path %>

app/views/fafsa_apps/new.html.erb
<h1 class="heading bg"> See if You Meet the Basic Qualifications</h1>



<%= render 'form1', fafsa_app: @fafsa_app %>

app/views/fafsa_apps/show.html.erb
 
 
<h2 class="bg"> Looks like you qualify! Finish the app to make sure! </h2> 

test
    <p>
      <strong>Received aid before? </strong>
      <%= @fafsa_app.receive_aid %>
    </p>

    <p>
      <strong>For what year are you applying?:</strong>
      <%= @fafsa_app.application_year %>
    </p>
    <p>
       <strong>What grade or year are you in?</strong>
      <%= @fafsa_app.current_grade %>
  </p>

  <p>
      <strong>Do you have a bachelors now OR will have one by the start of your application year?</strong>
      <%= @fafsa_app.bachelors %> 
  </p>

  <p>
      <strong>What type of degree are you trying to get?</strong>
      <%= @fafsa_app.degree_applied %>
  </p>

  <p>
      <strong>Conviction:</strong>
      <%= @fafsa_app.conviction %>
  </p>

  <p>

        <strong>Citizenship status?:</strong>
  
        <%= @fafsa_app.citizen %>

    
  </p>
    <p>
      <strong>Alien num:</strong>
       <%= @fafsa_app.alien_num %>
       </p>
  <p>
    <strong>High school:</strong>
 
  <%= @fafsa_app.high_school %>
 
</p>
 


<%= link_to 'Complete My App', edit_fafsa_app_path(@fafsa_app), class:'nav submit' %> 
<hr>





<p>
 <strong>Do you have a Drivers license:</strong>
 <%= @fafsa_app.drivers_license %>
</p>

<p>
 <strong>In which state did you get your Drivers license?</strong>
 <%= @fafsa_app.drivers_license_st %>
</p>

<p>
 <strong>whats your Drivers license number?:</strong>
 <%= @fafsa_app.drivers_license_num %>
</p>

<p>
 <strong>Interesed in Work Study:</strong>
 
 <%= @fafsa_app.work_study %>
 
</p>

<p>
 <strong>Foster care:</strong>
 
 <%= @fafsa_app.foster_care %>
 
</p>

<p>
 <strong>Which high school did you go to?</strong>
 
 <%= @fafsa_app.high_school_name %>
 
</p>
<p>
 <strong>Which city was your high school in?</strong>
 
 <%= @fafsa_app.high_school_city %>
 
</p>

<p>
 <strong>And, which state was your high school in?</strong>
 
 <%= @fafsa_app.high_school_state %>
 
</p>

<p>
 <strong>Housing plans while your in college?</strong>
 
 <%= @fafsa_app.housing_plans %>
 
</p>
<p>
 <strong>Do you have kids that you provide more than 50% of their care?</strong>
 
 <%= @fafsa_app.kids%>
 
</p>
<p>
 <strong>Maritial status</strong>
 
 <%= @fafsa_app.married%>
 
</p>
<p>
 <strong>Do you have any one that is more than 50% dependent on you?</strong>
 
 <%= @fafsa_app.dep %>
 
</p>


<p>
 <strong>Parent educational history</strong>
 <%= @fafsa_app.parent_edu %>
</p>

<p>
 <strong>Parent educational history</strong>
 <%= @fafsa_app.parent_edu2 %>
</p>

<%= link_to ' File My App!',{ controller: "fafsa_apps", action: "submit" } , {class:'nav submit'} %> |

<%= link_to 'Edit My App', edit_fafsa_app_path(@fafsa_app),  {class:'nav submit'} %> 

app/views/home/info.html.erb
this will have more resources in cards with links

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FAFSA Helper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@200;400;700&display=swap" rel="stylesheet">
  </head>
    
    <body >
    <%= render partial: "shared/header" %>
      <%= render partial: "shared/navbar" %>
       
        <div class="container">
          <div class='inner-container'>
            <%= yield  %>
          </div>
        </div>  
        <%= render partial: "shared/footer" %>
    </body>
</html>

app/views/shared/_footer.html.erb
<nav >
    <ul >
       
    
       <li> <%= link_to 'Resources', home_info_path, class:"a" %>
   
    
</nav>

app/views/shared/_header.html.erb
<h1 class="header"> FAFSA Helper </h1> 

app/views/shared/_navbar.html.erb
<nav >
    <ul class="nav">
       <li class="current"> <%= link_to 'Home', home_index_path, class:"a"%>
    
       <li> <%= link_to 'Resources', home_info_path, class:"a" %>
   
             <% if user_signed_in? %> 
       <li>     <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"a"%>
       <li>     <%= link_to "My Account", current_user, class:"a"%>
             <% else %>
       <li>     <%= link_to "Create An Account", new_user_registration_path, class:"a"%>
       <li>     <%= link_to "Log In", new_user_session_path, class:"a"%>
             <% end %>
    </ul>
</nav>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= user.username %><br/>
    <%= user.email %><br/>
  <% end %>

app/views/users/show.html.erb
<% if @user.student == "I am the student" %>
           <h2> Student Account Details </h2> 
           <h3> Hi, <%=@user.username%>! </h3>
        <% elsif @user.student == "I am a parent" %>
        <h2> Parent Account Details </h2> 
        <% else %>
        <h2>  Account Details </h2>  
         <% end %>   

<div class="big-box">

    <div class="small-box">

         <h5> Name: <%= @user.first_name%> <%=@user.last_name%></h5>
        <h5><%=@user.dob.to_s.unpack('A4xA2xA2').rotate.join('/')%></h5>

        
        <h5> Street Address: <%=@user.address%></h5>
        <h5> City: <%=@user.city %> </h5>
        <h5> State: <%=@user.state %> </h5>
        <h5> Zip Code: <%=@user.zip %> </h5>
<hr>
        <h2> Contact Details </h2>
        <h5>Phone number:<%= @user.phone%></h5>
        <h5>Email: <%= @user.email%></h5>
        
     

        
        <%= link_to 'Edit Account', edit_user_registration_path, class:'nav' %>
    </div>

    <div class="small-box l">

        <p> Kudos! Good on you for taking the first steps to secure your education! One of the best things you can do is to apply for a Federal Pell Grant. Click the link below to see if you might prequalify. </p>

        <h3> What Exactly is a Federal Pell Grant? </h3>
        <p> A Pell Grant is fund provided by the Federal that you do not have to repay as long certain conditions are meant.</p> 
            <p> It is basically free money for school as long as you keep your grades up and meet the other criteria. </p>
            <p> BUT a Pell grant is not the only funds you can get to pay for school</p> 
        <%= link_to "See if you meet the basic qualifications", new_fafsa_app_path,  class:'nav submit' %>
    </div>
</div>